all: run1 run2 run3 run4 run5 run6

run1:
	@echo "Running 1.py"
	@python3 1.py

run2:
	@echo "Running 2.py"
	@python3 2.py

run3:
	@echo "Running 3.py"
	@python3 3.py

run4:
	@echo "Running 4.py"
	@python3 4.py

run5:
	@echo "Running 5.py"
	@python3 5.py

run6:
	@echo "Running 6.py"
	@python3 6.py
